stages:

  feature_engg:
    cmd: python src/features/build_features.py data/raw/orders.csv
    deps:
      - data/raw/orders.csv
      - src/features/build_features.py
    outs:
      - data/processed/data_feature_engg.csv

  make_dataset:
    cmd: python src/data/make_dataset.py data/processed/data_feature_engg.csv
    deps:
      - data/processed/data_feature_engg.csv
      - src/data/make_dataset.py
    params:
      - make_dataset.test_split
      - make_dataset.seed
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  feature_selection:
    cmd: python src/features/feature_selection.py data/processed/train.csv data/processed/test.csv
    deps:
      - data/processed/train.csv
      - data/processed/test.csv
      - src/features/feature_selection.py
    outs:
      - data/processed/selected_train.csv
      - data/processed/selected_test.csv

  preprocessing:
    cmd: python src/preprocessing/preprocessing.py data/processed
    deps:
      - data/processed/selected_train.csv
      - data/processed/selected_test.csv
      - src/preprocessing/preprocessing.py
    outs:
      - data/processed/X_train_trf.csv
      - data/processed/X_test_trf.csv
      - models/preprocessor.pkl

  train_model:
    cmd: python src/models/train_model.py data/processed
    deps:
      - data/processed/X_train_trf.csv
      - data/processed/X_test_trf.csv
      - data/processed/selected_train.csv
      - data/processed/selected_test.csv
      - src/models/train_model.py
    params:
      - model

  tune_model:
    cmd: python src/models/tune_model.py data/processed
    deps:
      - data/processed/X_train_trf.csv
      - data/processed/selected_train.csv
      - src/models/tune_model.py
    params:
      - tuning.C

  train_final_model:
    cmd: python src/models/train_final_model.py data/processed
    deps:
      - data/processed/X_train_trf.csv
      - data/processed/X_test_trf.csv
      - data/processed/selected_train.csv
      - data/processed/selected_test.csv
      - src/models/train_final_model.py
    params:
      - final_model
    outs:
      - models/return_risk_model.pkl

metrics:
  - dvclive/metrics.json